# Generated by Django 4.2.1 on 2023-06-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='reating_avg',
            new_name='rating_avg',
        ),
    ]
