# Generated by Django 4.2.1 on 2023-06-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_rename_reating_avg_game_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='artist',
            field=models.ManyToManyField(blank=True, to='recommender.artist'),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(blank=True, to='recommender.category'),
        ),
        migrations.AlterField(
            model_name='game',
            name='designer',
            field=models.ManyToManyField(blank=True, to='recommender.designer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gametype',
            field=models.ManyToManyField(blank=True, to='recommender.gametype'),
        ),
        migrations.AlterField(
            model_name='game',
            name='maxplayers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mechanic',
            field=models.ManyToManyField(blank=True, to='recommender.mechanic'),
        ),
        migrations.AlterField(
            model_name='game',
            name='minage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='minplayers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_voters',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='playingtime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_avg',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating_geek',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='weight',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
