# Generated by Django 4.2.1 on 2023-06-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_alter_game_maxplayers_alter_game_minage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mechanic',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='gametype',
            name='slug',
            field=models.SlugField(default='', max_length=30),
        ),
    ]
