# Generated by Django 4.2.1 on 2023-06-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_alter_rating_game_alter_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_rec',
            field=models.ManyToManyField(blank=True, to='recommender.game'),
        ),
    ]
